server:
  port: 8088
file:
  directory: photos
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/accidents
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.xml
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true

datasource:
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
